# fly.toml app configuration file generated for assetflow-purple-wave-9522 on 2025-09-04T00:45:05+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assetflow-purple-wave-9522'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
